//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int empno { get; set; }
        public string ename { get; set; }
        public string job { get; set; }
        public int manager { get; set; }
        public System.DateTime hireddate { get; set; }
        public double salary { get; set; }
        public double commission { get; set; }
        public int deptno { get; set; }
    }
}
